graph TD
    A((เริ่ม)) --> B{กระบวนการพร้อมทำงาน?};
    B -- ไม่พร้อม --> F((จบ));
    B -- พร้อม --> C[ดึงข้อมูล CSC];
    C --> D[ตรวจสอบ/ดึงข้อมูลย่อย];
    D --> E[เพิ่มข้อมูล WinSpeed];
    E --> G((จบ));
    
    F --> H[รอรอบถัดไป]
    H --> A
    G --> H