graph TD
B[เรียก API เป้าหมาย] --> C{ได้ Response 2xx ไหม}

C -- ใช่ --> F[บันทึก Log SUCCESS]
F --> K[ไปขั้นตอน C]

C -- ไม่ --> E[ErrorHandler บันทึก Log และ ErrorCode]

E --> R{ผลลัพธ์จาก ErrorHandler}

R -- RETRY --> B
R -- DEAD --> H[ส่งไป DeadQueue]


H --> B_End[จบขั้นตอน B ด้วยสถานะล้มเหลว]
